import legalListCom from '@/sub-pages/ccm/custview/outline/legal-proceed/components/legal-list.vue';
import { codeTranslate } from '@/hook/code-hook';
import { fmtThousands, fmtDate } from '@/utils/format';

import {
  courtDeclaredList,
  filingInfoList,
  courtBulletinList,
  riskLawsuitList,
  executionList,
  execillegalList,
  limitHighConsumList,
  finalInfoList,
  judicialAuctionList,
  properiyPreservationList,
} from '@/apis/cust';

export const legalList = [
  {
    legalName: '法院公告',
    apiUrl: courtDeclaredList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '公告类型', prop: 'annType' },
      { label: '公告人（法院）', prop: 'courtName' },
      { label: '当事人', prop: 'partyPlaintiff' },
      { label: '原始当事人', prop: 'origPartyPlaintiff' },
      { label: '公告时间', prop: 'publicDate' },
      { label: '公告内容', prop: 'article' },
    ],
    total: 0,
  },
  {
    legalName: '立案信息',
    apiUrl: filingInfoList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '案由', prop: 'caseCause' },
      { label: '立案日期', prop: 'filingDate' },
      { label: '标的金额', prop: 'executionObject', formatter: (row: any) => fmtThousands(row.executionObject, 2) },
      { label: '当事人', prop: 'applExecutor' },
      { label: '案件状态', prop: 'caseStast' },
      { label: '执行法院', prop: 'courtName' },
    ],
  },
  {
    legalName: '开庭公告',
    apiUrl: courtBulletinList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '案由', prop: 'caseCause' },
      { label: '当事人', prop: 'partyPlaintiff' },
      { label: '法院', prop: 'court' },
      { label: '开庭日期', prop: 'lawfulDate' },
    ],
  },
  {
    legalName: '裁判文书',
    apiUrl: riskLawsuitList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案件号', prop: 'caseNo' },
      { label: '标题', prop: 'title' },
      { label: '案件当事人列表', prop: 'partyPerson' },
      { label: '涉案金额', prop: 'caseAum', formatter: (row: any) => fmtThousands(row.caseAum, 2) },
      { label: '审判日期', prop: 'judgeTime' },
      { label: '判决结果', prop: 'result' },
      { label: '法院名称', prop: 'courtName' },
    ],
  },
  {
    legalName: '被执行企业',
    apiUrl: executionList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '被执行人', prop: 'executee' },
      { label: '执行法院', prop: 'courtname' },
      { label: '执行标的', prop: 'executionObject' },
      { label: '立案日期', prop: 'filingDate' },
    ],
  },
  {
    legalName: '失信被执行企业',
    apiUrl: execillegalList,
    comp: shallowRef(legalListCom),

    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '被执行人', prop: 'executee' },
      { label: '执行法院', prop: 'courtname' },
      { label: '履行情况', prop: 'performance' },
      { label: '失信行为', prop: 'detail' },
      { label: '立案日期', prop: 'filingDate' },
      { label: '发布日期', prop: 'pubdate' },
    ],
  },
  {
    legalName: '限制高消费',
    apiUrl: limitHighConsumList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '被执行人', prop: 'executee' },
      { label: '申请执行人', prop: 'applicant' },
      { label: '执行金额', prop: 'exeAum', formatter: (row: any) => fmtThousands(row.exeAum, 2) },
      { label: '限制原因', prop: 'limitReason' },
      { label: '立案日期', prop: 'filingDate' },
      { label: '案件状态', prop: 'caseStast' },
      { label: '执行法院', prop: 'courtname' },
      { label: '发布日期', prop: 'pubdate' },
    ],
  },
  {
    legalName: '终本信息',
    apiUrl: finalInfoList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '被执行人', prop: 'executee' },
      { label: '执行标的', prop: 'executionObject' },
      { label: '未执行金额', prop: 'unexeAum', formatter: (row: any) => fmtThousands(row.unexeAum, 2) },
      { label: '执行法院', prop: 'courtname' },
      { label: '立案日期', prop: 'filingDate' },
      { label: '终本日期', prop: 'endDate' },
    ],
  },
  {
    legalName: '司法拍卖',
    apiUrl: judicialAuctionList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案号', prop: 'caseNo' },
      { label: '标题', prop: 'title' },
      { label: '标的物名称', prop: 'subjectName' },
      { label: '被执行人', prop: 'executee' },
      { label: '起拍价', prop: 'startPrice', formatter: (row: any) => fmtThousands(row.startPrice, 2) },
      { label: '成交价', prop: 'endPrice', formatter: (row: any) => fmtThousands(row.endPrice, 2) },
      { label: '拍卖状态', prop: 'auctionStast' },
      { label: '执行法院', prop: 'courtname' },
      { label: '公告日期', prop: 'publicDate' },
    ],
  },
  {
    legalName: '财产保全',
    apiUrl: properiyPreservationList,
    comp: shallowRef(legalListCom),
    fields: [
      { label: '案由', prop: 'caseCause' },
      { label: '案号', prop: 'caseNo' },
      { label: '案件类型', prop: 'caseType' },
      { label: '立案日期', prop: 'filingDate' },
      { label: '法院名称', prop: 'courtName' },
      { label: '裁判日期', prop: 'judgeTime' },
      { label: '判决金额', prop: 'judgAum', formatter: (row: any) => fmtThousands(row.judgAum, 2) },
      { label: '判决结果', prop: 'result' },
    ],
  },
];
